<script type='text/javascript' src='<?php echo base_url('static/js/skip-link-focus-fix.min.js'); ?>'></script>
<script type='text/javascript' src='<?php echo base_url('static/js/html5.min.js'); ?>'></script>
<script type='text/javascript' src='<?php echo base_url('static/js/superfish.min.js'); ?>'></script>
<script type='text/javascript' src='<?php echo base_url('static/js/jquery.flexslider-min.js'); ?>'></script>
<script type='text/javascript' src='<?php echo base_url('static/js/jquery.tools.min.js'); ?>'></script>
<script type='text/javascript' src='<?php echo base_url('static/js/jquery.jcarousel.min.js'); ?>'></script>
<script type='text/javascript' src='<?php echo base_url('static/js/jquery.cokie.min.js'); ?>'></script>
<script type='text/javascript' src='<?php echo base_url('static/js/jquery.elastislide.min.js'); ?>'></script>
<script type='text/javascript' src='<?php echo base_url('static/js/jquery-ui.custom.min.js'); ?>'></script>
<script type='text/javascript' src='<?php echo base_url('static/js/jquery.mobilemenu.min.js'); ?>'></script>
<script type='text/javascript' src='<?php echo base_url('static/js/jquery.validate.min.js'); ?>'></script>
<script type='text/javascript' src='<?php echo base_url('static/js/common.min.js'); ?>'></script>
<script type='text/javascript' src='<?php echo base_url('static/js/main.min.js'); ?>'></script>